name: CD

on:
  push:
    branches:
      - cse
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-arm64:
    name: Build ARM64 Image
    runs-on: arm64
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: hub.pingcap.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and Push Images
        uses: docker/build-push-action@v2
        with:
          context: ./cluster-autoscaler
          platforms: "linux/arm64"
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          tags: hub.pingcap.net/sunxiaoguang/serverless/cluster-autoscaler:${{ github.sha }}-arm64
  build-amd64:
    name: Build AMD64 Image
    runs-on: amd64
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: hub.pingcap.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and Push Images
        uses: docker/build-push-action@v2
        with:
          context: ./cluster-autoscaler
          platforms: "linux/amd64"
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          tags: hub.pingcap.net/sunxiaoguang/serverless/cluster-autoscaler:${{ github.sha }}-amd64
  multi-arch:
    name: Create Multi-Architecture Image
    runs-on: amd64
    needs: ["build-arm64", "build-amd64"]
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: hub.pingcap.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: create-manifest
        run: |
          docker manifest create hub.pingcap.net/sunxiaoguang/serverless/cluster-autoscaler:${{ github.sha }} \
          --amend hub.pingcap.net/sunxiaoguang/serverless/cluster-autoscaler:${{ github.sha }}-amd64 \
          --amend hub.pingcap.net/sunxiaoguang/serverless/cluster-autoscaler:${{ github.sha }}-arm64
      - name: push-manifest
        run: |
          docker manifest push hub.pingcap.net/sunxiaoguang/serverless/cluster-autoscaler:${{ github.sha }}
